services:
  flask-api:
    image: vijethegde/fake_review_api:latest
    container_name: ai_api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
    restart: always

  review-scraper:
    image: vijethegde/scraper_api:latest
    container_name: scraper_api
    ports:
      - "8069:3000"
    environment:
      - PORT=3000
      - AMAZON_EMAIL=${AMAZON_EMAIL}
      - AMAZON_PASSWORD=${AMAZON_PASSWORD}
    volumes:
      - ./data:/usr/src/app/data
    shm_size: 2gb
