services:
  review-scraper:
    build: .
    ports:
      - "8069:3000"
    env_file:
      - ./.env
    environment:
      - PORT=3000
    volumes:
      - ./data:/usr/src/app/data
      - ./reviews.json:/usr/src/app/reviews.json
    shm_size: 2gb
