version: '3.8'

services:
  review-scraper:
    image: vijethegde/scraper-api:latest
    ports:
      - "8069:3000"
    environment:
      - PORT=3000
      - AMAZON_EMAIL=${AMAZON_EMAIL}
      - AMAZON_PASSWORD=${AMAZON_PASSWORD}
    volumes:
      - ./data:/usr/src/app/data
      - ./reviews.json:/usr/src/app/reviews.json
    shm_size: 2gb 

